### ISSUE TITLE
Make vn.train generic

### ISSUE THREAD

**Issue by zainhoda** [vanna-ai/vanna-py#22]
vn.train should take in

question: str or None
sql: str or None
ddl: str or None
documentation: str or None
json_file: str or None
sql_file: str or None

- If just question, throw an error and print out example usage
- If just sql, do vn.generate_question to generate the question and then vn.add_sql
- If just DDL, do vn.add_ddl
- If just documentation, do vn.store_documentation
- If just a json_file, read the json file using pd.read_json and then iterate through rows to get question and sql columns to do vn.add_sql
- If just a sql_file, use sqlparse to separate the sql statements. Anything that's a create table should go into vn.add_DDL and other statements should do vn.generate_question and then vn.add_sql

All parameters defaults should be None and if the user passes in any combination of invalid parameters it should raise an exception

**Comment by MichaelMMeskhi** [comment]
Is the json file mode removed? I am looking for a way to iteratively add pairs into vector DB. Or should I write my own loop instead?

**Comment by zainhoda** [comment]
@MichaelMMeskhi Yes, it has been removed -- `for` loop is the way to go. We found that it was actually more work for people to get their files into a specific format and then read them compared to just writing 3 lines along the lines of:

```python
training_data = pd.read_...
for item in training_data:
   vn.train(...)
```

**Comment by MichaelMMeskhi** [comment]
Thank you @zainhoda !
