### ISSUE TITLE
Restrict the characters that can be in a dataset name

### ISSUE THREAD

**Issue by zainhoda** [vanna-ai/vanna-py#28]
In order to avoid confusion and also to make the dataset name url safe, on input of the dataset name we should:
- make it lowercase
- replace spaces with a hyphen `-`
- replace special characters with hyphen or remove it altogether

There should be a deterministic mapping of the input dataset string to the actual dataset name so that users can do vn.set_dataset('my WEirD dataset name!') and it will still work

**Comment by arslanhashmi** [comment]
https://github.com/vanna-ai/vanna-py/pull/34
